from __future__ import annotations


def build_auto_translator_config(
    *,
    language: str,
    from_language: str = "auto",
    override_font: str = "NotoSansSC_sdf32_optimized_12k_lz4_2020",
    endpoint: str = "CustomTranslate",
    custom_url: str = "http://127.0.0.1:14366/translate",
) -> str:
    return f"""[Service]
Endpoint={endpoint}
FallbackEndpoint=

[General]
Language={language}
FromLanguage={from_language}

[Files]
Directory=Translation\\{{Lang}}\\Text
OutputFile=Translation\\{{Lang}}\\Text\\_AutoGeneratedTranslations.txt
SubstitutionFile=Translation\\{{Lang}}\\Text\\_Substitutions.txt
PreprocessorsFile=Translation\\{{Lang}}\\Text\\_Preprocessors.txt
PostprocessorsFile=Translation\\{{Lang}}\\Text\\_Postprocessors.txt

[TextFrameworks]
EnableIMGUI=True
EnableUGUI=True
EnableNGUI=True
EnableTextMeshPro=True
EnableTextMesh=True
EnableFairyGUI=True

[Behaviour]
MaxCharactersPerTranslation=1000
IgnoreWhitespaceInDialogue=True
MinDialogueChars=20
ForceSplitTextAfterCharacters=0
CopyToClipboard=False
MaxClipboardCopyCharacters=2500
ClipboardDebounceTime=1.25
EnableUIResizing=True
EnableBatching=True
UseStaticTranslations=True
OverrideFont={override_font}
OverrideFontSize=
OverrideFontTextMeshPro={override_font}
FallbackFontTextMeshPro=
ResizeUILineSpacingScale=
ForceUIResizing=False
IgnoreTextStartingWith=\\u180e;
TextGetterCompatibilityMode=False
GameLogTextPaths=
RomajiPostProcessing=ReplaceMacronWithCircumflex;RemoveApostrophes;ReplaceHtmlEntities
TranslationPostProcessing=ReplaceMacronWithCircumflex;ReplaceHtmlEntities
RegexPostProcessing=
CacheRegexPatternResults=False
PersistRichTextMode=Final
CacheRegexLookups=False
CacheWhitespaceDifferences=False
GenerateStaticSubstitutionTranslations=False
GeneratePartialTranslations=False
EnableTranslationScoping=True
EnableSilentMode=True
BlacklistedIMGUIPlugins=
EnableTextPathLogging=False
OutputUntranslatableText=False
IgnoreVirtualTextSetterCallingRules=False
MaxTextParserRecursion=1
HtmlEntityPreprocessing=True
HandleRichText=True
EnableTranslationHelper=False
ForceMonoModHooks=False
InitializeHarmonyDetourBridge=False
RedirectedResourceDetectionStrategy=AppendMongolianVowelSeparatorAndRemoveAll
OutputTooLongText=False
TemplateAllNumberAway=False
ReloadTranslationsOnFileChange=False
DisableTextMeshProScrollInEffects=False
CacheParsedTranslations=False

[Texture]
TextureDirectory=Translation\\{{Lang}}\\Texture
EnableTextureTranslation=False
EnableTextureDumping=False
EnableTextureToggling=False
EnableTextureScanOnSceneLoad=False
EnableSpriteRendererHooking=False
LoadUnmodifiedTextures=False
DetectDuplicateTextureNames=False
DuplicateTextureNames=
EnableLegacyTextureLoading=False
TextureHashGenerationStrategy=FromImageName
CacheTexturesInMemory=True
EnableSpriteHooking=False

[ResourceRedirector]
PreferredStoragePath=Translation\\{{Lang}}\\RedirectedResources
EnableTextAssetRedirector=False
LogAllLoadedResources=False
EnableDumping=False
CacheMetadataForAllFiles=True

[Http]
UserAgent=
DisableCertificateValidation=True

[TranslationAggregator]
Width=400
Height=100
EnabledTranslators=

[Debug]
EnableConsole=False

[Migrations]
Enable=True
Tag=5.3.0

[Custom]
Url={custom_url}
"""


def build_rei_patcher_ini(exe_name: str) -> str:
    stem = exe_name.rsplit(".", 1)[0]
    return f""";{exe_name} - ReiPatcher Configuration File
;
[ReiPatcher]
PatchesDir=Patches
AssembliesDir=..\\{stem}_Data\\Managed

[Launch]
Executable=..\\{exe_name}
Arguments=
Directory=..\\

[Assemblies]
UnityEngine.CoreModule=UnityEngine.CoreModule.dll
"""
